site_name: ja_timex documentation
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list
  - attr_list
  - admonition
theme:
    name: material
    language: ja
    icon:
        logo: material/av-timer
        repo: fontawesome/brands/git-alt
    favicon: favicon.png
    features:
      - navigation.expand
extra_css:
  - stylesheets/extra.css
nav:
    - "Home": index.md
    - "User Guide":
      - installation.md
      - quick_start.md
      - examples.md
      - timex3.md
      - FAQ.md
      - definition_glossary.md
      - policy.md
    - "Release":
      - changelog.md
