name: Run Tox in Multiple Environments

on:
  pull_request

jobs:
  build:
    runs-on: ${{matrix.platform}}
    if: contains(github.head_ref, 'feature') || contains(github.head_ref, 'fix')
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install poetry tox
    - name: Test with tox
      run: poetry run tox